name: social-buying-web-client
services:
  appserver:
    type: node
    build:
      - yarn install
tooling:
  yarn:
    service: appserver
proxy:
  appserver:
    - social-buying-web-client.lndo.site:3000
