name: social-buying-web-client
services:
  appserver:
    type: node
    port: '3000'
    build:
      - yarn install
  nginx:
    type: nginx
    ssl: true
    webroot: app/public
    config:
      vhosts: config/custom.conf
tooling:
  yarn:
    service: appserver
proxy:
  appserver:
    - social-buying-web-client.lndo.site:3000
