name: social-buying-web-client
services:
  appserver:
    type: node
    build:
      - echo "REACT_APP_API_URL=http://social-buying-web-client.lndo.site" > '.env.local'
      - yarn install
tooling:
  yarn:
    service: appserver
proxy:
  appserver:
    - social-buying-web-client.lndo.site:3000
